# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0993f698ce1cd7fc560b6f689d2708cef60a541eb0871532b037a7d9266cb9c986f4c60330493eb0ccc1bb9cb06624c4988d4d89afa2982d814158bac40f5b01

test:
  secret_key_base: 70d4643a80fb2638925ac814da07bb8258242ab1904edcb2a469efb23ef9e0262cc06ea1df9196bbcc9e7bb431278260c423613f86cbff0f383757a6f5808ff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
